### ISSUE TITLE
Syncing will be stuck after it was interrupted once

### ISSUE THREAD

**Issue by linkdesu** [nervosnetwork/mercury#281] opened 2021-11-04 08:41 UTC
**What happened**:
I first stopped the mercury container while it is syncing, then when I start it again I found it log not updating any more, after enable debug log I found the mercury just keep requesting `get_block_by_number` API again and again.

Here is the log of mercury: http://tmp.link/f/6183a1c91695d

**What you expected to happen**:
Keep syncing after restart.

**How to reproduce it (as minimally and precisely as possible)**:
Stop it while syncing or try it with my docker-compose configs here https://github.com/linkdesu/ckb-env .

**Anything else we need to know?**:
Why I stopped the container while it is syncing? Becasue I found the config `log_path` is a path to directory but not a file.
And when I config it to the directory of where the config.toml, in my container it is `/data`, it will not write log any more, I think it is may be a small bug, but it can be avoid by config, so I just metion it here.

**Environment**:

- Mercury version or commit hash (`git log -1`): v0.2.0-beta.3
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.3 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu-server 5.4.0-81-generic
- Others:  Docker version 20.10.10, build b485636

Thanks for your help.

**Comment by KaoImin** [comment] 2021-11-08 12:43
This issue is caused by a bug of the judge whether needs to sync. It has been fixed by #283.

**Closed** 2021-11-09 02:25 UTC
